name: "Compile code"

on:
  push:
  workflow_dispatch:

jobs:
  compile:
    name: Compile the codebase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Compile
      run: |-
        make build